theme: jekyll-theme-cayman
title: Delphi Clean Architecture
description: Study to implement Clean Architecture in a Delphi application to prove that this concept can be applied to Delphi as well.\nSpecial thanks to Uncle Bob and all authors from Clean Architecture.
show_downloads: false